name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ejecuta el Workflow cuando haya un push en la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Usa Node.js versión 16

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construir el proyecto
      - name: Build project
        run: npm run build

      # 5. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token de autenticación
          publish_dir: ./dist # Carpeta que contiene los archivos generados por Vite